# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'fidgetswipe-ios' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for fidgetswipe-ios
  
  pod 'Firebase'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Performance'

  target 'fidgetswipe-iosTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'fidgetswipe-iosUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
